# Generated by Django 2.0 on 2018-01-10 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lablog', '0002_auto_20180110_2305'),
    ]

    operations = [
        migrations.RenameModel('BookInstance', 'Record'),
    ]
