# Generated by Django 2.0 on 2018-01-11 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lablog', '0005_auto_20180111_0041'),
    ]

    operations = [
    ]
