# Generated by Django 2.0 on 2018-01-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lablog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='feedback',
        ),
        migrations.AddField(
            model_name='experiment',
            name='feedback',
            field=models.ManyToManyField(help_text='Select a stimulae for this experiment', to='lablog.Feedback'),
        ),
    ]
