# Generated by Django 2.0 on 2018-01-10 22:10

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('lablog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel('Book', 'Experiment')
    ]
