# Generated by Django 2.0 on 2018-01-10 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lablog', '0001_squashed_0003_auto_20180110_2226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='book',
            new_name='experiment',
        ),
    ]
