# Generated by Django 2.0 on 2018-01-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lablog', '0002_auto_20180116_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='feedback',
            field=models.ManyToManyField(help_text='Select a feedback for this experiment', to='lablog.Feedback'),
        ),
    ]
