# Generated by Django 2.0 on 2018-01-10 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lablog', '0002_auto_20180110_2210'),
    ]

    operations = [
        #migrations.RenameField('BookInstance', 'Book', 'Experiment'),
        #migrations.RenameField('Author', 'Book', 'Experiment'),
        #migrations.RenameField('Genre', 'Book', 'Experiment'),
        #migrations.RenameField('Language', 'Book', 'Experiment'),
    ]
