# Generated by Django 2.0 on 2018-01-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lablog', '0003_auto_20180116_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='subject',
        ),
        migrations.AddField(
            model_name='experiment',
            name='subject',
            field=models.ManyToManyField(to='lablog.Subject'),
        ),
    ]
