# Generated by Django 2.0 on 2018-01-11 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lablog', '0003_auto_20180110_2355'),
    ]

    operations = [
    ]
