# Generated by Django 2.0 on 2018-01-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lablog', '0004_auto_20180116_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiment',
            old_name='subject',
            new_name='subjects',
        ),
        migrations.AddField(
            model_name='subject',
            name='experiments',
            field=models.ManyToManyField(to='lablog.Experiment'),
        ),
    ]
