# Generated by Django 2.0 on 2018-01-11 00:41

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('lablog', '0004_auto_20180111_0004'),
    ]

    operations = [
        migrations.RenameModel('Author', 'Subject')
    ]
