# Generated by Django 2.0 on 2018-01-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lablog', '0005_auto_20180116_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'permissions': (('can_change_status', 'Set record status'),)},
        ),
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.CharField(blank=True, choices=[('d', 'Maintenance'), ('a', 'Available'), ('r', 'Restricted')], default='d', help_text='Record status', max_length=1),
        ),
    ]
