# Generated by Django 2.0 on 2018-01-18 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lablog', '0006_auto_20180116_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a observation arrangement.)', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='observation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lablog.Observation'),
        ),
    ]
