# Generated by Django 2.0 on 2018-01-18 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lablog', '0007_auto_20180118_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='due_back',
            new_name='rec_date',
        ),
    ]
