# Generated by Django 2.0 on 2018-04-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lablog', '0008_auto_20180118_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='experiments',
        ),
        migrations.AddField(
            model_name='subject',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
