# Generated by Django 2.0 on 2018-04-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lablog', '0009_auto_20180403_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='name',
        ),
        migrations.AddField(
            model_name='feedback',
            name='analysis',
            field=models.CharField(default='default', help_text='Analysis setup', max_length=100),
        ),
        migrations.AddField(
            model_name='feedback',
            name='electrode1',
            field=models.IntegerField(default=1, help_text='Position of first electrode'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='electrode2',
            field=models.IntegerField(default=1, help_text='Position of second electrode'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='electrode3',
            field=models.IntegerField(default=1, help_text='Position of third electrode'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='electrode4',
            field=models.IntegerField(default=1, help_text='Position of fourth electrode'),
        ),
    ]
