# Generated by Django 2.0 on 2018-04-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lablog', '0010_auto_20180403_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='stimulae',
            name='media1',
            field=models.FileField(default='/dev/null', help_text='First media file', upload_to=''),
        ),
        migrations.AddField(
            model_name='stimulae',
            name='media2',
            field=models.FileField(default='/dev/null', help_text='Optional media file', null=True, upload_to=''),
        ),
    ]
