# Generated by Django 2.0 on 2018-04-05 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lablog', '0011_auto_20180403_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='observation',
        ),
        migrations.DeleteModel(
            name='Observation',
        ),
    ]
