# Generated by Django 2.0 on 2018-04-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lablog', '0012_auto_20180405_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='attendant',
        ),
        migrations.RemoveField(
            model_name='record',
            name='experiment',
        ),
        migrations.RemoveField(
            model_name='record',
            name='imprint',
        ),
        migrations.RemoveField(
            model_name='record',
            name='rec_date',
        ),
        migrations.RemoveField(
            model_name='record',
            name='status',
        ),
        migrations.RemoveField(
            model_name='record',
            name='subject',
        ),
        migrations.AddField(
            model_name='record',
            name='EEG',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='record',
            name='ObservationMedia1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='record',
            name='ObservationMedia2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='record',
            name='StartTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='StopTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='TENSControl',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
