# Generated by Django 2.0 on 2018-04-07 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lablog', '0013_auto_20180406_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='isbn',
        ),
        migrations.AddField(
            model_name='experiment',
            name='DateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='records',
            field=models.ManyToManyField(blank=True, help_text='Select a records for this experiment', to='lablog.Record'),
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='feedback',
        ),
        migrations.AddField(
            model_name='experiment',
            name='feedback',
            field=models.OneToOneField(default=1, help_text='Select a feedback for this experiment', on_delete=django.db.models.deletion.PROTECT, to='lablog.Feedback'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='stimulae',
        ),
        migrations.AddField(
            model_name='experiment',
            name='stimulae',
            field=models.OneToOneField(default=1, help_text='Select a stimulae for this experiment', on_delete=django.db.models.deletion.PROTECT, to='lablog.Stimulae'),
            preserve_default=False,
        ),
    ]
