# Generated by Django 2.0.4 on 2018-04-10 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lablog', '0014_auto_20180407_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='feedback',
            field=models.ForeignKey(help_text='Select a feedback for this experiment', on_delete=django.db.models.deletion.PROTECT, to='lablog.Feedback'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='stimulae',
            field=models.ForeignKey(help_text='Select a stimulae for this experiment', on_delete=django.db.models.deletion.PROTECT, to='lablog.Stimulae'),
        ),
    ]
