# Generated by Django 2.0.4 on 2018-04-18 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lablog', '0017_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='analysis',
            field=models.ForeignKey(help_text='Select a analysis for this Feedback', on_delete=django.db.models.deletion.PROTECT, to='lablog.Analysis'),
        ),
    ]
